language: python
sudo: true

python:
  - "2.7"
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - fab test
  - fab start
  - fab status
  - sudo cat /tmp/wikirandom/wikirandoms_err.log
