jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '2.7', '3.7', 'pypy3' ]
    name: WikiRandom
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          fabric3
          architecture: x64
      - run: fab test
